name: publish
on:
  push:
    branches:
      - master
jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd intercept/
            git fetch
            git reset --hard origin/master
            rvm use ruby-3.0.0
            ruby -v
            bundle install
            rerun 'rackup'
