name: publish
on:
  push:
    branches:
      - master
jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.HOST }} ${{ secrets.USER }} ${{ secrets.KEY }}"
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd intercept/
            git fetch
            git reset --hard origin/master
            bundle install
            rerun 'rackup'
